### ISSUE TITLE
Branch not appearing in "Cron Jobs"

### ISSUE THREAD

**Issue by wtanaka** [travis-ci/beta-features#12]
This branch:
https://github.com/wtanaka/ansible-role-oracle-java/tree/dev

is not showing up in "Cron Jobs" in:
https://travis-ci.org/wtanaka/ansible-role-oracle-java/settings

and I would have expected it to.

**Comment by joshk** [comment]
Hi @wtanaka 

Please use the issues listed in https://github.com/travis-ci/beta-features/issues for commenting on Beta Features, or if you are running into a bug, can you please email support@travis-ci.com

Thanks a bundle

Josh

**Comment by florenthemmi** [comment]
Hello,

Clicking on the "Beta feature" badge redirect here.
But the correct issue seems #27.

<img width="540" alt="screen shot 2017-08-28 at 08 38 50" src="https://user-images.githubusercontent.com/4488419/29762003-687685aa-8bcc-11e7-8a5a-a9858c40818a.png">

Can you fix this glitch?
Thanks!
