### ISSUE TITLE
Please add a UI workflow to export travis.yml

### ISSUE THREAD

**Issue by noloader** [travis-ci/beta-features#15]
I am trying to export `travis.yml` to see what the web UI added as the daily cron job. Though I used the web UI to enable the cron job, we use `travis.yml` because its easier to manage. Additionally, other can use the  `travis.yml` we supply with the project (in contrast to my web UI settings , which no one gets to see or utilize).

Appveyor had a similar request at [Export YML from project configuration](http://help.appveyor.com/discussions/suggestions/256-export-yml-from-project-configuration). It was well received by the devs, and it serves the community well. Additionally, Appveyor allows one to validate the YML file before committing changes to it.

My apologies if the feature is already present. I'm in the repo's settings, and I only see four headings (General, Auto Cancellation, Environment Variables, Cron Jobs). I also don't see a discussion of the YML in [Cron Jobs](https://docs.travis-ci.com/user/cron-jobs/).

**Comment by joshk** [comment]
Hi @noloader  

Can you please open an issue at https://github.com/travis-ci/travis-ci/issues.

This repository is only for discussing currently released Beta Features.

Thanks

Josh
