### ISSUE TITLE
add pagination to /hooks api-call to make it more scalable

### ISSUE THREAD

**Issue by kaizhu256** [travis-ci/beta-features#16]
i can forsee scalability issues if one has say 10,000+ repos while making the /hooks api-call. maybe something like
https://api.travis-ci.org/hooks?limit=100&offset=9000

 would alleviate this problem?

**Comment by joshk** [comment]
Hi @kaizhu256 

The issues for this repository are meant for discussion on Beta Features we have released, or plan to release.

Could you please re-open this issue on our main issue tracking repository at https://github.com/travis-ci/travis-ci

Thanks

Josh
