### ISSUE TITLE
Auto-retry failed builds

### ISSUE THREAD

**Issue by lacostenycoder** [travis-ci/beta-features#17]
Many of our front-end Capybara tests fail randomly but will pass upon retry builds.
Although we will work to improve our tests so this doesn't happen, it would be great if we could have a way to request auto-retry builds `n` number of times.

**Comment by tianon** [comment]
If there's one specific part of your job that's consistently having this issue, you could try `travis_retry` (https://docs.travis-ci.com/user/common-build-problems/#travis_retry). :smile: :+1:

**Comment by joshk** [comment]
Hi, could you please use the `travis-ci/travis-ci` repo for feature requests. This issue tracker is only for features which have been released in our Beta program.

Thanks

Josh
