### ISSUE TITLE
Crons: Build every hours

### ISSUE THREAD

**Issue by redaxmedia** [travis-ci/beta-features#2]
I use one of my cronjobs for reinstalling a CMS demo from a master branch each day - it would be awesome to build the demo every hour. Other people may need this to refresh a dev or stage environment.

**Comment by icemac** [comment]
To me this looks like a misuse of a CI system. If you keep your master branch clean (by protecting the master branch in github and only allowing merging of successfully tested pull requests) you should be able to re-install your demo system using a cron on its own machine directly from the master branch.

**Comment by redaxmedia** [comment]
Not everyone does have a dedicated server my friend, but thank you for your great advice. It was eye opening to me.

**Comment by thangngoc89** [comment]
You can use AWS lambda to retrigger the CI build that costs almost nothing

**Comment by joshk** [comment]
Thanks for the suggestion and feedback.

I'm sorry but we ask that you don't create issues in this repo, but only use it for providing feedback to issues open by Travis team members for current features which are in beta.

This feedback would best sit in https://github.com/travis-ci/beta-features/issues/1

Thanks a bundle

Josh
