### ISSUE TITLE
Stage ignore script command

### ISSUE THREAD

**Issue by gw4e** [travis-ci/beta-features#20]
Hi,
I have the following stage:
language:
  java
  
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: test
      script: ./runmvnprofile.sh gw4e-eclipse-plugin-tests
      script: ./runmvnprofile.sh gw4e-eclipse-plugin-ui-tests
      script: ./runmvnprofile.sh gw4e-eclipse-studio-tests
      script: ./runmvnprofile.sh gw4e-eclipse-studio-ui-tests

The runmvnprofile.sh  is as follows 
#!/bin/bash

if [ "$1" != "" ]; then
    mvn clean install -P$1
else
    echo "Profile parameter is missing"
fi

Unfortunately the stages are not taken into account. The shell script is not called instead mvn command are executed  **_mvn test -B_** 
I dont know where these commands came from.

Any idea of how can I launch shell in parallel ?

Thanks.

**Comment by joshk** [comment]
Hi there

Can you please open issues, relating to bugs or problems you are running into, at https://github.com/travis-ci/travis-ci/issues

Thanks a bundle

Josh
