### ISSUE TITLE
Documentation is misleading

### ISSUE THREAD

**Issue by gw4e** [travis-ci/beta-features#21]
Hi
The doc states the following : 
jobs:
  include:
    - script: ./test 1 # uses the default stage name "test"
    - script: ./test 2
    - stage: deploy
      script: ./deploy target-1
    - script: ./deploy target-2

When applying this to my case it was not working. See https://github.com/travis-ci/travis-ci/issues/7846

The error came from a **_matrix.include_**  usage. The configuration section should mention what are the constraints.

**Comment by joshk** [comment]
Hi @gw4e 

Can you please open this issue on our public issue tracker at https://github.com/travis-ci/travis-ci/issues

Thanks a bundle

Josh
