### ISSUE TITLE
Star and follow other people's Repositories

### ISSUE THREAD

**Issue by j3mdamas** [travis-ci/beta-features#24]
Is would be interesting if we could star other people's repositories in order to follow builds of repositories I care about on a single Dashboard, instead of having to navigate to other people's pages

**Comment by Nader-Zubaid** [comment]
[0.46.0-rc.2] Bump version numbers

**Comment by Nader-Zubaid** [comment]
https://g.co/kgs/AioCpL

**Comment by backspace** [comment]
Hello, @j3mdamas! Do you mind posting that to the [dashboard feedback thread](https://github.com/travis-ci/beta-features/issues/5) rather than in a separate issue? Thanks. 😀

**Comment by j3mdamas** [comment]
Thanks, done it.
