### ISSUE TITLE
search for pagination

### ISSUE THREAD

**Issue by daggerok** [travis-ci/beta-features#29]
Hello!

Is that right place to tell you about user experience?

After pagination you introduce in Account page, it's hard to find needed project to enable it build. I have a lot of repositories (200+) and for me it's very inconvenient

Before, my flow was next: I just synced repositories with my github account and using command+F was able to quickly find target repo and toggling ON/OFF button, but now is not possible. Right now I see only one useful way to do that: type manually repository travis uri: /$account-name/$repository-name and activate build here

**Comment by backspace** [comment]
Do you mind opening this in the issue tracker?

> This isn’t the place for feature requests or bug reports. If that’s what you’ve come here for, please either visit our [public bug tracker](https://github.com/travis-ci/travis-ci/issues) or send us an email at support@travis-ci.org.
