### ISSUE TITLE
Branch dedup in beta

### ISSUE THREAD

**Issue by softprops** [travis-ci/beta-features#3]
There was mention of a beta feature in the readme of a project that addressed https://github.com/travis-ci/travis-ci/issues/964 - https://github.com/grosser/travis_dedup/blob/master/Readme.md

Is that still true and if so are there any docs on the feature (in beta)?

**Comment by joshk** [comment]
Thanks for the suggestion and feedback.

I'm sorry but we ask that you don't create issues in this repo, but only use it for providing feedback to issues open by Travis team members for current features which are in beta.

This feature is not in public beta at this time. Although we should have it ready for GA release later this month.

Thanks a bundle

Josh
