### ISSUE TITLE
Hanging Build since > 11h

### ISSUE THREAD

**Issue by nolte** [travis-ci/beta-features#30]
Hi,

at the moment i have a "hanging", but faild stage build since ca 11h, [look](https://travis-ci.org/nolte/noltarium-blog/builds/279812042)

it is ok that the Development Stage faild, because some test faild, [34.1](https://travis-ci.org/nolte/noltarium-blog/jobs/279812043) and [34.2](https://travis-ci.org/nolte/noltarium-blog/jobs/279812044) !

The next Stage (#34.3) was skipped ... like the Stage Build shout work, but the Last stage [34.4](https://travis-ci.org/nolte/noltarium-blog/jobs/279812046) are are executed ... i thinking that is a Error. 

the build are not cancelled after [#37](https://travis-ci.org/nolte/noltarium-blog/builds/280042451) runned.  

the bug has no impact for me ... all other builds run fine !!! 

thanks for the nice Service !

**Comment by joshk** [comment]
Closing as this issue is stale.
