### ISSUE TITLE
jcchimjj@yahoo.com

### ISSUE THREAD

**Issue by JcChimjj** [travis-ci/beta-features#34]
Hello!

This isn’t the place for feature requests or bug reports. If that’s what you’ve come here for, please either visit our [public bug tracker](https://github.com/travis-ci/travis-ci/issues) or send us an email at support@travis-ci.org.

Otherwise, go ahead and delete this text :grimacing:

**Comment by vitalkanev** [comment]
What's this? Please close the issue
