### ISSUE TITLE
Public bug tracker

### ISSUE THREAD

**Issue by saifulke** [travis-ci/beta-features#39]
Hello!

This isn’t the place for feature requests or bug reports. If that’s what you’ve come here for, please either visit our [public bug tracker](https://github.com/travis-ci/travis-ci/issues) or send us an email at support@travis-ci.org.

Otherwise, go ahead and delete this text :grimacing:

**Comment by backspace** [comment]
Hey, maybe you opened this in the wrong place? Please see the template message and use one of those links. 😀
