### ISSUE TITLE
[Multiple Jobs] - Show average or max time vs total

### ISSUE THREAD

**Issue by wltjr** [travis-ci/beta-features#44]
Not so much a bug or feature request as more something for discussion. I noticed after switching to multiple jobs. When I look at the build history. The time seemed rather excessive. I thought it was making the builds take longer. Instead its showing a total of all build times combined. Which I guess makes sense as to total build time. But I think it makes more sense for like an average, or to display the max time from any one. Given that they all run together, the actual time is really no longer than the time of the longest one. Or the time to run all stages, which still seems less than time of all combined.

Example history, pretty easy to see without any other information other than build times when I switched to multiple jobs.
https://travis-ci.org/Obsidian-StudiosInc/entrance/builds

I have no preference really either way just feedback. At first I thought something might be off.

**Comment by joshk** [comment]
As Stages is now released and GA, I'm going to close this issue.

If you have any feedback on improvements we should consider, please feel free to add a discussion in our new Community forum: https://travis-ci.community/c/product

Happy building

Josh
