### ISSUE TITLE
Secured variable with build stages

### ISSUE THREAD

**Issue by LaurentGoderre** [travis-ci/beta-features#49]
I'm having difficulties with using build stages with secured variable

https://travis-ci.org/nodejs/docker-node/jobs/362173107#L460
https://github.com/nodejs/docker-node/blob/build-test2/.travis.yml#L48-L49

Am I doing something wrong?

**Comment by kenman345** [comment]
I think you're encrypting the wrong thing. For the GH token, to include it in your `.travis.yml` itself you would want to encrypt the token name with the value:
`GITHUB_API_TOKEN=[GITHUB_API_TOKEN value goes here]` and then insert that into your `.travis.yml`

alternatively, you could type in `GITHUB_API_TOKEN` in the [settings](https://travis-ci.org/nodejs/docker-node/settings)->Environment Variables menu for Travis-CI.org and then input the token value into the variables field and make sure it says "OFF" for the 'Display value in build log' option before hitting `Add`. When you add it this way, you wont even need to worry its not being involved in a particular build, as its going to be imported to every build and will never show the true value. It will not be available to users forks off the repository though, even on PRs to that repository

**Comment by LaurentGoderre** [comment]
Thanks, I found the issue. I meant to close this before.
