### ISSUE TITLE
Deploy stage broken?

### ISSUE THREAD

**Issue by kenman345** [travis-ci/beta-features#51]
#So I am running Travis-CI with the beta stages feature and its been working well except recently. I made a change to add in that the job that runs our deploys can also work when we run a cron job once a week since it deploys our site which should always be ready to deploy.

So I made the following change (and a follow-up commit just to fix the spacing of course):
https://github.com/acceptbitcoincash/acceptbitcoincash/commit/0d4bf194f57c56635b07febf4c5b6471e0bf672e#diff-354f30a63fb0907d4ad57269548329e3L41

It worked well when I had set up my cron job and I was happy to get the 4-25-2018 tagged docker container that appeared here: https://hub.docker.com/r/acceptbitcoincash/acceptbitcoincash/tags/

Today I went to tag the repository, which under normal circumstances will force a build of the docker container and then a tag of the current date, and deploy to docker hub.

The tag build started but then failed to identify that variable should change. Okay, my fault I thought. So I went ahead and fixed it to force it to go into the path I wanted. 

Well, that did not work. Instead, I got the following message with my build:
https://travis-ci.org/acceptbitcoincash/acceptbitcoincash/jobs/373285943#L704 

What is not permitted about? My only condition for that deploy to go is that its got that variable changed. That was most certainly the case on my four attempts where I got variations of that message.

**Comment by kenman345** [comment]
I am quite thoroughly upset. Where are conditions not working aas they always have for deploy stages? 

https://travis-ci.org/acceptbitcoincash/acceptbitcoincash/jobs/373295617#L704

I removed a ton of the small parts of the `.travis.yml` file in order to 100% get it to the right state and its still not working. I've now muddied my repository with 5 tags that all didnt work as expected. I'm gonna set up another cron job just for now to get what I want but this is absurd that something that should work and logically is set up perfectly is not working when it was just a week ago.

**Comment by cotsog** [comment]
@kenman345 Could you please open an issue in our [public bug tracker](https://github.com/travis-ci/travis-ci/issues) for this?

> This isn’t the place for feature requests or bug reports. If that’s what you’ve come here for, please either visit our [public bug tracker](https://github.com/travis-ci/travis-ci/issues) or send us an email at support@travis-ci.org.

Thanks!
