### ISSUE TITLE
GM 

### ISSUE THREAD

**Issue by GeorgeMAKULU** [travis-ci/beta-features#53]
Hello!

This isn’t the place for feature requests or bug reports. If that’s what you’ve come here for, please either visit our [public bug tracker](https://github.com/travis-ci/travis-ci/issues) or send us an email at support@travis-ci.org.

Otherwise, go ahead and delete this text :grimacing:

**Comment by cotsog** [comment]
Please let us know if there's something specific we can help you with over at https://github.com/travis-ci/travis-ci.
