### ISSUE TITLE
Comic Sans is good if you have Monospaced Comic Sans

### ISSUE THREAD

**Issue by galeksandrp** [travis-ci/beta-features#7]
So please fix my logs with [that](https://github.com/belluzj/fantasque-sans) or Courier/Courier New.

**Comment by joshk** [comment]
Hi @galeksandrp 

Can you please open this on the https://github.com/travis-ci/travis-ci issue tracker as this repo is only for the announcement of beta features.

Thank you

Josh

**Comment by galeksandrp** [comment]
travis-ci/travis-ci#7442
